/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.4
 * Generated at: 2023-01-31 08:19:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.study;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class record_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/kosmo/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1672711024185L));
    _jspx_dependants.put("jar:file:/C:/Users/kosmo/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602841572000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 8 ]><html class=\"ie\" xmlns=\"http://www.w3.org/1999/xhtml\"\r\n");
      out.write("xml:lang=\"en-US\" lang=\"en-US\"> <![endif]-->\r\n");
      out.write("<!--[if (gte IE 9)|!(IE)]><!-->\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-US\" lang=\"en-US\">\r\n");
      out.write("    <!--<![endif]-->\r\n");
      out.write("    <!-- 한글 깨짐 방지-->\r\n");
      out.write("    \r\n");
      out.write("        <!DOCTYPE html>\r\n");
      out.write("        <!--[if IE 8 ]><html class=\"ie\" xmlns=\"http://www.w3.org/1999/xhtml\"\r\n");
      out.write("        xml:lang=\"en-US\" lang=\"en-US\"> <![endif]-->\r\n");
      out.write("        <!--[if (gte IE 9)|!(IE)]><!-->\r\n");
      out.write("        <html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-US\" lang=\"en-US\">\r\n");
      out.write("            <!--<![endif]-->\r\n");
      out.write("\r\n");
      out.write("            <!-- JSTL 사용-->\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("                <head>\r\n");
      out.write("                    <!-- Basic Page Needs -->\r\n");
      out.write("                    <meta charset=\"utf-8\">\r\n");
      out.write("                    <!--[if IE]><meta http-equiv='X-UA-Compatible'\r\n");
      out.write("                    content='IE=edge,chrome=1'><![endif]-->\r\n");
      out.write("                    <title>HOWSTUDY</title>\r\n");
      out.write("\r\n");
      out.write("                    <meta name=\"author\" content=\"themesflat.com\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Mobile Specific Metas -->\r\n");
      out.write("                    <meta\r\n");
      out.write("                        name=\"viewport\"\r\n");
      out.write("                        content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Theme Style -->\r\n");
      out.write("                    <link rel=\"stylesheet\" type=\"text/css\" href=\"../assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- myStudy Style-->\r\n");
      out.write("                    <link rel=\"stylesheet\" type=\"text/css\" href=\"../assets/css/mystudy.css\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Favicon and Touch Icons -->\r\n");
      out.write("                    <link rel=\"shortcut icon\" href=\"../assets/icon/Favicon.png\">\r\n");
      out.write("                    <link rel=\"apple-touch-icon-precomposed\" href=\"../assets/icon/Favicon.png\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- 타이머 -->\r\n");
      out.write("                    <link\r\n");
      out.write("                        href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\"\r\n");
      out.write("                        rel=\"stylesheet\"\r\n");
      out.write("                        integrity=\"sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN\"\r\n");
      out.write("                        crossorigin=\"anonymous\">\r\n");
      out.write("                    <script type=\"text/javascript\" src=\"record.js\"></script>\r\n");
      out.write("\r\n");
      out.write("                    <!-- chart.js -->\r\n");
      out.write("                    <script\r\n");
      out.write("                        src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js\"></script>\r\n");
      out.write("                </head>\r\n");
      out.write("                <style>\r\n");
      out.write("                    * {\r\n");
      out.write("                        margin: 0;\r\n");
      out.write("                        padding: 0;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("            .box {\r\n");
      out.write("                width: 200px;\r\n");
      out.write("               \r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .timerBox {\r\n");
      out.write("                width: 350px;\r\n");
      out.write("              \r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .timerBox .time {\r\n");
      out.write("                font-size: 30pt;\r\n");
      out.write("                color: #4C4C4C;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                font-family: sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btnBox {\r\n");
      out.write("                left: 135px;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                margin: 20px auto;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btnBox .fa {\r\n");
      out.write("                margin: 0 5px;\r\n");
      out.write("                font-size: 30pt;\r\n");
      out.write("                color: #FAED7D;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("\r\n");
      out.write("                <body class=\"body header-fixed is_dark connect-wal\">\r\n");
      out.write("                    <div id=\"wrapper\">\r\n");
      out.write("                        <div id=\"page\" class=\"clearfix\">\r\n");
      out.write("                            <!-- header 넣음 -->\r\n");
      out.write("                            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("                            <!-- Header -->\r\n");
      out.write("                            <!-- body section-->\r\n");
      out.write("                            <section class=\"tf-item tf-section\">\r\n");
      out.write("                                <div class=\"themesflat-container\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-box-12\">\r\n");
      out.write("                                    <div class=\"flat-tabs items\">\r\n");
      out.write("                                        <ul class=\"menu-tab\">\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"../study/record?mId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                                    <span>RECORD</span></a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"../study/ranking\">\r\n");
      out.write("                                                    <span>RANKING</span></a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"../study/todo?mId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                                    <span>TO-DO</span></a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"../study/note?mId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                                    <span>NOTE</span></a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"content-tab\">\r\n");
      out.write("                                        <div class=\"content-inner\">\r\n");
      out.write("                                            <div class=\"content-item\">\r\n");
      out.write("                                                <div class=\"sc-box-icon no-box-shadown mgbt-0 none\"></div>\r\n");
      out.write("                                                <!-- 여기임 -->\r\n");
      out.write("                                                <!-- main section-->\r\n");
      out.write("                                                <section\r\n");
      out.write("                                                    class=\"tf-section live-auctions style4 home4 live-auctions-style7\">\r\n");
      out.write("                                                    <!-- 닉네임 출력 -->\r\n");
      out.write("                                                    <div class=\"themesflat-container\">\r\n");
      out.write("                                                        <div class=\"row\">\r\n");
      out.write("                                                            <div class=\"col-box-12\">\r\n");
      out.write("                                                                <div class=\"heading-live-auctions\">\r\n");
      out.write("                                                                    ");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /WEB-INF/views/study/record.jsp(138,68) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId!=null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                                                        <h2 class=\"tf-title pb-40 text-left\"\r\n");
            out.write("                                                                            style=\"margin-top: 3%;\">\r\n");
            out.write("                                                                            ");
            out.print(session.getAttribute("loginId"));
            out.write("\r\n");
            out.write("                                                                                님의 스터디룸\r\n");
            out.write("                                                                        </h2>\r\n");
            out.write("                                                                    ");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("<!-- 타이머 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"fl-collection fl-item3 col-box-4\" style=\"display: block;top: 17px;position: relative;\">\r\n");
      out.write("    <div class=\"sc-card-collection style-2 sc-card-style7\">\r\n");
      out.write("    <div id='box' class=\"box\">\r\n");
      out.write("        <div id='timerBox' class=\"timerBox\">\r\n");
      out.write("            <span id=\"time\" class=\"time\"\r\n");
      out.write("                style=\"color: white;\">00:00:00</span>\r\n");
      out.write("                <span class=\"btnBox\">\r\n");
      out.write("                    <i id=\"startbtn\" class=\"fa fa-play\"\r\n");
      out.write("                        aria-hidden=\"true\"></i>\r\n");
      out.write("                    <i id=\"pausebtn\" class=\"fa fa-pause\"\r\n");
      out.write("                        aria-hidden=\"true\"></i>\r\n");
      out.write("                    <i id=\"stopbtn\" class=\"fa fa-stop checkbutton\"\r\n");
      out.write("                        aria-hidden=\"true\"></i>\r\n");
      out.write("                </span>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("    <input type=\"hidden\" class=\"sNum\" value=\"1050\">\r\n");
      out.write("    <!-- 방번호 체크용-->\r\n");
      out.write("    \r\n");
      out.write("        <!-- <button class=\"checkbutton\">체크버튼</button>/ -->\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                \r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            \r\n");
      out.write("\r\n");
      out.write("                                                            <!-- 오늘 공부한 시간 출력 -->\r\n");
      out.write("                                                            <div class=\"fl-collection fl-item3 col-box-4\">\r\n");
      out.write("                                                                <div class=\"sc-card-collection style-2 sc-card-style7\">\r\n");
      out.write("                                                                    <div class=\"card-header\"\r\n");
      out.write("                                                                    style=\"color : var(--primary-color);border-radius: 1rem;width:50%;left: 107px;position: relative;\">\r\n");
      out.write("                                                                        <h3 style=\"left: 12%;position: inherit;color: #ff8787;\">오늘 공부 시간</h3>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"card-bottom\">\r\n");
      out.write("                                                                        <div class=\"author\" style=\"margin: 0 auto;\">\r\n");
      out.write("                                                                            <div class=\"content\">\r\n");
      out.write("                                                                                <h4>\r\n");
      out.write("                                                                                    <span\r\n");
      out.write("                                                                                        id=\"todaystudytimes\" style=\"font-size: 50px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time.todayStudyTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                                                                                </h4>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    \r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <!-- 일 평균 공부한 시간 출력 -->\r\n");
      out.write("                                                            <div class=\"fl-collection fl-item3 col-box-4\">\r\n");
      out.write("                                                                <div class=\"sc-card-collection style-2 sc-card-style7\">\r\n");
      out.write("                                                                    <div\r\n");
      out.write("                                                                        class=\"card-header\"\r\n");
      out.write("                                                                        style=\"color : var(--primary-color);border-radius: 1rem;width:50%;left: 107px;position: relative;\">\r\n");
      out.write("                                                                        <h3 style=\"left: 2%;position: inherit;color: #ff8787;\">일 평균 공부 시간</h3>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"card-bottom\">\r\n");
      out.write("                                                                        <div class=\"author\" style=\"margin: 0 auto;\">\r\n");
      out.write("                                                                            <div class=\"content \">\r\n");
      out.write("                                                                                <h4>\r\n");
      out.write("                                                                                    <span id=\"todayaveragetimes\" style=\"font-size: 50px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time.todayAvgTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></h4>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <!-- 전체 공부한 시간 출력 -->\r\n");
      out.write("                                                            <div class=\"fl-collection fl-item3 col-box-4\" style=\"display: block;\">\r\n");
      out.write("                                                                <div class=\"sc-card-collection style-2 sc-card-style7\">\r\n");
      out.write("                                                                    <div class=\"card-header\"\r\n");
      out.write("                                                                    style=\"color : var(--primary-color);border-radius: 1rem;width:50%;left: 107px;position: relative;\">\r\n");
      out.write("                                                                        <h3 style=\"left: 12%;position: inherit;color: #ff8787;\">전체 공부 시간</h3>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"card-bottom\">\r\n");
      out.write("                                                                        <div class=\"author\" style=\"margin: 0 auto;\">\r\n");
      out.write("                                                                            <div class=\"content \">\r\n");
      out.write("                                                                                <h4>\r\n");
      out.write("                                                                                    <span\r\n");
      out.write("                                                                                        id=\"totalstudytime\" style=\"font-size: 50px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time.totalStudyTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                                                                                </h4>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                            \r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </section>\r\n");
      out.write("                                                <!-- section finish-->\r\n");
      out.write("                                                <div>\r\n");
      out.write("                                                    <!-- 누적 공부시간 section -->\r\n");
      out.write("                                                    <section class=\"col-md-12 col-lg-6\"\r\n");
      out.write("                                                        style=\"float: left; padding-top: 10%; \">\r\n");
      out.write("                                                        <!--//col-->\r\n");
      out.write("                                                        <div class=\"col-md-12 col-lg-6\">\r\n");
      out.write("                                                            <div class=\"app-card app-card-chart h-100 shadow-sm\">\r\n");
      out.write("                                                                <div class=\"app-card-header p-3\">\r\n");
      out.write("                                                                    <div\r\n");
      out.write("                                                                        class=\"row justify-content-between align-items-center\">\r\n");
      out.write("                                                                        <div class=\"col-auto\">\r\n");
      out.write("                                                                            <h4 class=\"app-card-title\">\r\n");
      out.write("                                                                                누적 공부시간 ( 날짜를 체크해주세요 )</h4>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <!--//col-->\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <!--//row-->\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <!--//app-card-header-->\r\n");
      out.write("                                                                <div class=\"app-card-body p-3 p-lg-4\">\r\n");
      out.write("                                                                    <div class=\"mb-3 d-flex\">\r\n");
      out.write("\r\n");
      out.write("                                                                                    <input\r\n");
      out.write("                                                                                        type=\"date\"\r\n");
      out.write("                                                                                        class=\"regdate1\"\r\n");
      out.write("                                                                                        id=\"regdate1\"\r\n");
      out.write("                                                                                        name=\"regdate1\"\r\n");
      out.write("                                                                                        onchange=\"checkDate1(event)\"\r\n");
      out.write("                                                                                       >\r\n");
      out.write("                                                                                    <span>~</span>\r\n");
      out.write("                                                                                    <input\r\n");
      out.write("                                                                                        type=\"date\"\r\n");
      out.write("                                                                                        class=\"regdate2\"\r\n");
      out.write("                                                                                        id=\"regdate2\"\r\n");
      out.write("                                                                                        name=\"regdate2\"\r\n");
      out.write("                                                                                        onchange=\"checkDate2(event)\"\r\n");
      out.write("                                                                                        >\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                                <div class=\"chart-container\">\r\n");
      out.write("                                                                                    <canvas\r\n");
      out.write("                                                                                        id=\"canvas-daychart\"\r\n");
      out.write("                                                                                        style=\"border-radius: 5px; height: 300px; width: 150%; \"></canvas>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                            <!--//app-card-body-->\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <!--//app-card-->\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <!--//col-->\r\n");
      out.write("                                                                </section>\r\n");
      out.write("                                                                <!-- 누적 공부시간 section finish-->\r\n");
      out.write("\r\n");
      out.write("                                                                <!-- 태그별 공부시간 section -->\r\n");
      out.write("                                                                <section class=\"col-md-12 col-lg-6\" style=\"float: right; padding-top: 10%; \">\r\n");
      out.write("                                                                    <!--//col-->\r\n");
      out.write("                                                                    <div class=\"col-md-12 col-lg-6\">\r\n");
      out.write("                                                                        <div class=\"app-card app-card-chart h-100 shadow-sm\">\r\n");
      out.write("                                                                            <div class=\"app-card-header p-3\">\r\n");
      out.write("                                                                                <div class=\"col-auto\">\r\n");
      out.write("                                                                                    <h4 class=\"app-card-title\">태그별 공부시간</h4>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                                <!--//row-->\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                            <!--//app-card-header-->\r\n");
      out.write("                                                                            <div class=\"app-card-body p-3 p-lg-4\">\r\n");
      out.write("\r\n");
      out.write("                                                                                <div class=\"chart-container\">\r\n");
      out.write("                                                                                    <canvas\r\n");
      out.write("                                                                                        id=\"canvas-tagchart\"\r\n");
      out.write("                                                                                        style=\"border-radius: 5px; height: 300px; width: 100%; \"></canvas>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                            <!--//app-card-body-->\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <!--//app-card-->\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <!--//col-->\r\n");
      out.write("                                                                </section>\r\n");
      out.write("                                                                <!-- 태그별 공부시간 section finish-->\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </section>\r\n");
      out.write("                                                        <!-- section finish-->\r\n");
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("                            <!-- body section finish-->\r\n");
      out.write("\r\n");
      out.write("                            <!-- Footer 넣음-->\r\n");
      out.write("                            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("                    <!-- /#page -->\r\n");
      out.write("\r\n");
      out.write("                    <!-- Modal Popup Bid -->\r\n");
      out.write("                    <div\r\n");
      out.write("                        class=\"modal fade popup\"\r\n");
      out.write("                        id=\"popup_bid_success\"\r\n");
      out.write("                        tabindex=\"-1\"\r\n");
      out.write("                        role=\"dialog\"\r\n");
      out.write("                        aria-hidden=\"true\">\r\n");
      out.write("                        <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("                            <div class=\"modal-content\">\r\n");
      out.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                                    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <div class=\"modal-body space-y-20 pd-40\">\r\n");
      out.write("                                    <h3 class=\"text-center\">Your Bidding Successfuly Added</h3>\r\n");
      out.write("                                    <p class=\"text-center\">your bid\r\n");
      out.write("                                        <span class=\"price color-popup\">(4ETH)\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                        has been listing to our database</p>\r\n");
      out.write("                                    <a href=\"href\" class=\"btn btn-primary\">\r\n");
      out.write("                                        Watch the listings</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div\r\n");
      out.write("                            class=\"modal fade popup\"\r\n");
      out.write("                            id=\"popup_bid\"\r\n");
      out.write("                            tabindex=\"-1\"\r\n");
      out.write("                            role=\"dialog\"\r\n");
      out.write("                            aria-hidden=\"true\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                    <div class=\"modal-body space-y-20 pd-40\">\r\n");
      out.write("                                        <h3>Place a Bid</h3>\r\n");
      out.write("                                        <p class=\"text-center\">You must bid at least\r\n");
      out.write("                                            <span class=\"price color-popup\">4.89 ETH</span>\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"00.00 ETH\">\r\n");
      out.write("                                        <p>Enter quantity.\r\n");
      out.write("                                            <span class=\"color-popup\">5 available</span>\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control quantity\" value=\"1\">\r\n");
      out.write("                                        <div class=\"hr\"></div>\r\n");
      out.write("                                        <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                            <p>\r\n");
      out.write("                                                You must bid at least:</p>\r\n");
      out.write("                                            <p class=\"text-right price color-popup\">\r\n");
      out.write("                                                4.89 ETH\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                            <p>\r\n");
      out.write("                                                Service free:</p>\r\n");
      out.write("                                            <p class=\"text-right price color-popup\">\r\n");
      out.write("                                                0,89 ETH\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                            <p>\r\n");
      out.write("                                                Total bid amount:</p>\r\n");
      out.write("                                            <p class=\"text-right price color-popup\">\r\n");
      out.write("                                                4 ETH\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <a\r\n");
      out.write("                                            href=\"#\"\r\n");
      out.write("                                            class=\"btn btn-primary\"\r\n");
      out.write("                                            data-toggle=\"modal\"\r\n");
      out.write("                                            data-target=\"#popup_bid_success\"\r\n");
      out.write("                                            data-dismiss=\"modal\"\r\n");
      out.write("                                            aria-label=\"Close\">\r\n");
      out.write("                                            Place a bid</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- /#wrapper -->\r\n");
      out.write("\r\n");
      out.write("                        <a id=\"scroll-top\"></a>\r\n");
      out.write("                        <script src=\"../assets/js/todo.js\"></script>\r\n");
      out.write("                        <script src=\"../assets/js/record.js\"></script>\r\n");
      out.write("                        <script\r\n");
      out.write("                            type=\"text/javascript\"\r\n");
      out.write("                            src=\"https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("                        <script\r\n");
      out.write("                            type=\"text/javascript\"\r\n");
      out.write("                            src=\"https://cdn.datatables.net/buttons/1.6.2/js/buttons.flash.min.js\"></script>\r\n");
      out.write("                        <script\r\n");
      out.write("                            type=\"text/javascript\"\r\n");
      out.write("                            src=\"https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js\"></script>\r\n");
      out.write("                        <script\r\n");
      out.write("                            type=\"text/javascript\"\r\n");
      out.write("                            src=\"https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js\"></script>\r\n");
      out.write("                        <script\r\n");
      out.write("                            type=\"text/javascript\"\r\n");
      out.write("                            src=\"https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js\"></script>\r\n");
      out.write("                        <script\r\n");
      out.write("                            type=\"text/javascript\"\r\n");
      out.write("                            src=\"https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js\"></script>\r\n");
      out.write("                        <script\r\n");
      out.write("                            type=\"text/javascript\"\r\n");
      out.write("                            src=\"https://cdn.datatables.net/buttons/1.6.2/js/buttons.print.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("                        <script\r\n");
      out.write("                            src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js\"></script>\r\n");
      out.write("                        <script\r\n");
      out.write("                            src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js\"></script>\r\n");
      out.write("                        <script src=\"https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0\"></script>\r\n");
      out.write("\r\n");
      out.write("                    </body>\r\n");
      out.write("\r\n");
      out.write("                </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
