/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.4
 * Generated at: 2023-01-31 02:51:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class modifyAccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 8]><html class=\"ie\" xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-US\" lang=\"en-US\"> <![endif]-->\r\n");
      out.write("<!--[if (gte IE 9)|!(IE)]><!-->\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-US\" lang=\"en-US\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("<!-- 한글 깨짐 방지-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Basic Page Needs -->\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <!--[if IE]><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" /><![endif]-->\r\n");
      out.write("    <title>HOWSTUDY</title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"author\" content=\"themesflat.com\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Mobile Specific Metas -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme Style -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../assets/css/style.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../assets/css/likeTag.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon and Touch Icons  -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"../assets/icon/Favicon.png\" />\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"../assets/icon/Favicon.png\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css\" />\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"body header-fixed is_dark connect-wal\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("      <div id=\"page\" class=\"clearfix\">\r\n");
      out.write("          <!-- header 넣음 -->\r\n");
      out.write("       ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- title page -->\r\n");
      out.write("        <section class=\"flat-title-page inner\">\r\n");
      out.write("          <div class=\"overlay\"></div>\r\n");
      out.write("          <div class=\"themesflat-container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-12\">\r\n");
      out.write("                <div class=\"page-title-heading mg-bt-12\">\r\n");
      out.write("                  <h1 class=\"heading text-center\">내 프로필</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"breadcrumbs style2\">\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li><a href=\"\">마이페이지</a></li>\r\n");
      out.write("                    <li>내 프로필</li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"tf-login tf-section\">\r\n");
      out.write("          <div class=\"themesflat-container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-12\">\r\n");
      out.write("                <h2 class=\"tf-title-heading ct style-1\">회원정보 수정</h2>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"flat-form box-login-email\">\r\n");
      out.write("                  <div class=\"form-inner\">\r\n");
      out.write("                    <form method=\"post\" id=\"modifyForm\" action=\"modifyForm\">\r\n");
      out.write("                      <input id=\"mId\" name=\"mId\" tabindex=\"1\" aria-required=\"true\" required type=\"text\"\r\n");
      out.write("                        value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly />\r\n");
      out.write("                      <input id=\"mPw\" name=\"mPw\" tabindex=\"2\" aria-required=\"true\" type=\"text\" placeholder=\"비밀번호\"\r\n");
      out.write("                        required />\r\n");
      out.write("                      <input name=\"mName\" tabindex=\"3\" value=\"\" aria-required=\"true\" type=\"text\" placeholder=\"이름\"\r\n");
      out.write("                        style=\"margin-top: 10px;\" />\r\n");
      out.write("                      <input name=\"mPhone\" tabindex=\"4\" value=\"\" aria-required=\"true\" type=\"text\" placeholder=\"전화번호\" />\r\n");
      out.write("                      <input name=\"mEmail\" tabindex=\"5\" value=\"\" aria-required=\"true\" type=\"text\" placeholder=\"이메일\" />\r\n");
      out.write("                      <div class=\"modifyBtn\" style=\"text-align: center; display: inline-block; width: 100%\">\r\n");
      out.write("              \r\n");
      out.write("                        <a href=\"../user/passwordConfirm?mId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.mId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></a>\r\n");
      out.write("                        <button class=\"submit\" id=\"modifyBtn\" type=\"submit\" name=\"modifyBtn\" style=\"width: 40%;\">\r\n");
      out.write("                          수정하기\r\n");
      out.write("                        </button></a>\r\n");
      out.write("                        <br> <br> <br>\r\n");
      out.write("                        <div class=\"box-title-login\">\r\n");
      out.write("                            <h5>서비스를 그만 이용 하시겠습니까?</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <div class=\"modifyBtn\" style=\"text-align: center; display: inline-block; width: 100%\">\r\n");
      out.write("                    <a href=\"../user/passwordConfirm?mId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.mId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                      <button style=\"width: 40%;\" id=\"deletecus\">\r\n");
      out.write("                        회원탈퇴\r\n");
      out.write("                      </button></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- 선호태그 모달 시작-->\r\n");
      out.write(" <form action=\"updatelikeTag\" id=\"updatelikeTag\" >\r\n");
      out.write("  <div class=\"modal fade popup\" id=\"popup_bid3\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"modal-body pd-40\" id=\"likeTagMargin\">\r\n");
      out.write("                <h3 style=\"margin-bottom: 30px;\">나의 관심 주제</h3>\r\n");
      out.write("                <input id=\"mId\" type=\"hidden\" name=\"mId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <label class=\"box-check-input\"><input type=\"checkbox\" class=\"likeTag\" name=\"mTag\" value=\"취업\"><span><img src=\"../assets/images/likeTag/취업.png\">취업</span></label>\r\n");
      out.write("                <label class=\"box-check-input\"><input type=\"checkbox\" class=\"likeTag\" name=\"mTag\" value=\"독서\"><span><img src=\"../assets/images/likeTag/독서.png\">독서</span></label>\r\n");
      out.write("                <label class=\"box-check-input\"><input type=\"checkbox\" class=\"likeTag\" name=\"mTag\" value=\"어학\" ><span><img src=\"../assets/images/likeTag/어학.png\">어학</span></label>\r\n");
      out.write("                <label class=\"box-check-input\"><input type=\"checkbox\" class=\"likeTag\" name=\"mTag\" value=\"임용\"><span><img src=\"../assets/images/likeTag/임용.png\">임용</span></label>\r\n");
      out.write("                <label class=\"box-check-input\"><input type=\"checkbox\" class=\"likeTag\" name=\"mTag\" value=\"공무원\"><span><img src=\"../assets/images/likeTag/공무원.png\">공무원</span></label>\r\n");
      out.write("                <label class=\"box-check-input\"><input type=\"checkbox\" class=\"likeTag\" name=\"mTag\" value=\"대학수능\"><span><img src=\"../assets/images/likeTag/대학수능.png\">대학수능</span></label>\r\n");
      out.write("                <label class=\"box-check-input\"><input type=\"checkbox\" class=\"likeTag\" name=\"mTag\" value=\"자격증\"><span><img src=\"../assets/images/likeTag/자격증.png\">자격증</span></label>\r\n");
      out.write("                <label class=\"box-check-input\"><input type=\"checkbox\" class=\"likeTag\" name=\"mTag\" value=\"학교공부\"><span><img src=\"../assets/images/likeTag/학교공부.png\">학교공부</span></label>\r\n");
      out.write("                <label class=\"box-check-input\"><input type=\"checkbox\" class=\"likeTag\" name=\"mTag\" value=\"기타\" ><span><img src=\"../assets/images/likeTag/기타.png\">기타</span></label>\r\n");
      out.write("                <label class=\"box-check-input\"><input type=\"checkbox\" class=\"likeTag\" name=\"mTag\" value=\"코딩\"><span><img src=\"../assets/images/likeTag/코딩.png\">코딩</span></label>\r\n");
      out.write("                <label class=\"box-check-input\"><input type=\"checkbox\" class=\"likeTag\" name=\"mTag\" value=\"이직\"><span><img src=\"../assets/images/likeTag/이직.png\">이직</span></label>\r\n");
      out.write("                <label class=\"box-check-input\"><input type=\"checkbox\" class=\"likeTag\" name=\"mTag\" value=\"자기계발\"><span><img src=\"../assets/images/likeTag/자기계발.png\">자기계발</span></label>\r\n");
      out.write("                \r\n");
      out.write("                <button id=\"likeTag\" style=\"margin-left: 136px; margin-top: 15px;\">선택 완료</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("<!--선호태그 모달 끝-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <!-- Bottom -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#page -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <a id=\"scroll-top\"></a>\r\n");
      out.write("    <script src=\"../assets/js/likeTag.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
