/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.4
 * Generated at: 2023-01-30 02:03:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 8]><html class=\"ie\" xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-US\" lang=\"en-US\"> <![endif]-->\r\n");
      out.write("<!--[if (gte IE 9)|!(IE)]><!-->\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-US\" lang=\"en-US\">\r\n");
      out.write("  <!--<![endif]-->\r\n");
      out.write("  <!-- 한글 깨짐 방지-->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Basic Page Needs -->\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <!--[if IE]><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" /><![endif]-->\r\n");
      out.write("    <title>HOWSTUDY</title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"author\" content=\"themesflat.com\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Mobile Specific Metas -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme Style -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../assets/css/style.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../assets/css/likeTag.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon and Touch Icons  -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/icon/Favicon.png\" />\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"assets/icon/Favicon.png\" />\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"body header-fixed is_dark connect-wal\">\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("      <div id=\"page\" class=\"clearfix\">\r\n");
      out.write("        <!-- header 넣음 -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("        <!-- title page -->\r\n");
      out.write("        <section class=\"flat-title-page inner\">\r\n");
      out.write("          <div class=\"overlay\"></div>\r\n");
      out.write("          <div class=\"themesflat-container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-12\">\r\n");
      out.write("                <div class=\"page-title-heading mg-bt-12\">\r\n");
      out.write("                  <h1 class=\"heading text-center\">회원가입</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"breadcrumbs style2\">\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li><a href=\"\">스터디룸</a></li>\r\n");
      out.write("                    <li>회원가입</li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"tf-login tf-section\">\r\n");
      out.write("          <div class=\"themesflat-container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-12\">\r\n");
      out.write("             \r\n");
      out.write("                <div class=\"flat-form box-login-social\">\r\n");
      out.write("                 \r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"flat-form box-login-email\">\r\n");
      out.write("                  <div class=\"box-title-login\">\r\n");
      out.write("                    <h5>H O W S T U D Y</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-inner\">\r\n");
      out.write("                    <form method=\"post\" id=\"insert-customer\" action=\"insertCustomer\">\r\n");
      out.write("                      <input\r\n");
      out.write("                        id=\"mId\"\r\n");
      out.write("                        name=\"mId\"\r\n");
      out.write("                        tabindex=\"1\"\r\n");
      out.write("                        aria-required=\"true\"\r\n");
      out.write("                        required\r\n");
      out.write("                        type=\"text\"\r\n");
      out.write("                        placeholder=\"아이디\"\r\n");
      out.write("                        required\r\n");
      out.write("                      />\r\n");
      out.write("                      <p id=\"chkNotice\" name=\"chkNotice\" size=\"2\" style=\"font-size: small\"></p>\r\n");
      out.write("                      <input\r\n");
      out.write("                        id=\"mPw\"\r\n");
      out.write("                        name=\"mPw\"\r\n");
      out.write("                        tabindex=\"3\"\r\n");
      out.write("                        aria-required=\"true\"\r\n");
      out.write("                        type=\"password\"\r\n");
      out.write("                        placeholder=\"비밀번호\"\r\n");
      out.write("                        required\r\n");
      out.write("                      />\r\n");
      out.write("                      <p id=\"chkNotice2\" name=\"chkNotice2\" size=\"2\" style=\"font-size: small\"></p>\r\n");
      out.write("                      <input\r\n");
      out.write("                        id=\"mPwchk\"\r\n");
      out.write("                        name=\"mPwchk\"\r\n");
      out.write("                        tabindex=\"3\"\r\n");
      out.write("                        aria-required=\"true\"\r\n");
      out.write("                        type=\"password\"\r\n");
      out.write("                        placeholder=\"비밀번호 재확인\"\r\n");
      out.write("                        required\r\n");
      out.write("                      />\r\n");
      out.write("                      <p id=\"chkNotice3\" name=\"chkNotice3\" size=\"2\" style=\"font-size: small\"></p>\r\n");
      out.write("                      <input\r\n");
      out.write("                        id=\"mName\"\r\n");
      out.write("                        name=\"mName\"\r\n");
      out.write("                        tabindex=\"3\"\r\n");
      out.write("                        aria-required=\"true\"\r\n");
      out.write("                        type=\"text\"\r\n");
      out.write("                        placeholder=\"이름\"\r\n");
      out.write("                        required\r\n");
      out.write("                      />\r\n");
      out.write("                      <p id=\"chkNotice4\" name=\"chkNotice4\" size=\"2\" style=\"font-size: small\"></p>\r\n");
      out.write("                      <input\r\n");
      out.write("                        id=\"mPhone\"\r\n");
      out.write("                        name=\"mPhone\"\r\n");
      out.write("                        tabindex=\"3\"\r\n");
      out.write("                        aria-required=\"true\"\r\n");
      out.write("                        type=\"text\"\r\n");
      out.write("                        placeholder=\"전화번호\"\r\n");
      out.write("                        required\r\n");
      out.write("                      />\r\n");
      out.write("                      <p id=\"chkNotice5\" name=\"chkNotice5\" size=\"2\" style=\"font-size: small\"></p>\r\n");
      out.write("                      <input\r\n");
      out.write("                        id=\"mEmail\"\r\n");
      out.write("                        name=\"mEmail\"\r\n");
      out.write("                        tabindex=\"2\"\r\n");
      out.write("                        aria-required=\"true\"\r\n");
      out.write("                        type=\"email\"\r\n");
      out.write("                        placeholder=\"이메일\"\r\n");
      out.write("                        required\r\n");
      out.write("                      />\r\n");
      out.write("                      <p id=\"chkNotice6\" name=\"chkNotice6\" size=\"2\" style=\"font-size: small\"></p>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"row-form style-1\">\r\n");
      out.write("                        <input type=\"button\" class=\"sc-button.fl-button.pri-3:hover\" data-toggle=\"modal\" data-target=\"#popup_bid\" name=\"signup\"  id=\"signup\" style=\"margin: auto;\"  value=\"가입하기\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                      <!-- <div class=\"flat-form box-login-social\">\r\n");
      out.write("                                            <button class=\"submit\" type=\"submit\" name=\"submit\"  class=\"sc-button.fl-button.pri-3:hover\" data-toggle=\"modal\" data-target=\"#popup_bid\" name=\"signup\"  id=\"signup\">가입하기</button>\r\n");
      out.write("                                        </div> -->\r\n");
      out.write("                                        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        \r\n");
      out.write("                                        <!-- 모달 시작-->\r\n");
      out.write("                      <div\r\n");
      out.write("                        class=\"modal fade popup\"\r\n");
      out.write("                        id=\"popup_bid\"\r\n");
      out.write("                        tabindex=\"-1\"\r\n");
      out.write("                        role=\"dialog\"\r\n");
      out.write("                        aria-hidden=\"true\"\r\n");
      out.write("                      >\r\n");
      out.write("                        <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("                          <div class=\"modal-content\">\r\n");
      out.write("                            <button\r\n");
      out.write("                              type=\"button\"\r\n");
      out.write("                              class=\"close\"\r\n");
      out.write("                              data-dismiss=\"modal\"\r\n");
      out.write("                              aria-label=\"Close\"\r\n");
      out.write("                            >\r\n");
      out.write("                              <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <div class=\"modal-body space-y-20 pd-40\">\r\n");
      out.write("                              <h3>나의 관심 주제</h3>\r\n");
      out.write("                              <input id=\"submitName\" type=\"hidden\" name=\"selectName\" value=\"\" />\r\n");
      out.write("                              <input id=\"submitPrice\" type=\"hidden\" name=\"selectPrice\" value=\"\" />\r\n");
      out.write("\r\n");
      out.write("                              <label class=\"box-check-input\"\r\n");
      out.write("                                ><input\r\n");
      out.write("                                  type=\"checkbox\"\r\n");
      out.write("                                  class=\"likeTag\"\r\n");
      out.write("                                  name=\"mTag\"\r\n");
      out.write("                                  value=\"취업\"\r\n");
      out.write("                                /><span\r\n");
      out.write("                                  ><img src=\"../assets/images/likeTag/취업.png\" />취업</span\r\n");
      out.write("                                ></label\r\n");
      out.write("                              >\r\n");
      out.write("                              <label class=\"box-check-input\"\r\n");
      out.write("                                ><input\r\n");
      out.write("                                  type=\"checkbox\"\r\n");
      out.write("                                  class=\"likeTag\"\r\n");
      out.write("                                  name=\"mTag\"\r\n");
      out.write("                                  value=\"독서\"\r\n");
      out.write("                                /><span\r\n");
      out.write("                                  ><img src=\"../assets/images/likeTag/독서.png\" />독서</span\r\n");
      out.write("                                ></label\r\n");
      out.write("                              >\r\n");
      out.write("                              <label class=\"box-check-input\"\r\n");
      out.write("                                ><input\r\n");
      out.write("                                  type=\"checkbox\"\r\n");
      out.write("                                  class=\"likeTag\"\r\n");
      out.write("                                  name=\"mTag\"\r\n");
      out.write("                                  value=\"어학\"\r\n");
      out.write("                                /><span\r\n");
      out.write("                                  ><img src=\"../assets/images/likeTag/어학.png\" />어학</span\r\n");
      out.write("                                ></label\r\n");
      out.write("                              >\r\n");
      out.write("                              <label class=\"box-check-input\"\r\n");
      out.write("                                ><input\r\n");
      out.write("                                  type=\"checkbox\"\r\n");
      out.write("                                  class=\"likeTag\"\r\n");
      out.write("                                  name=\"mTag\"\r\n");
      out.write("                                  value=\"임용\"\r\n");
      out.write("                                /><span\r\n");
      out.write("                                  ><img src=\"../assets/images/likeTag/임용.png\" />임용</span\r\n");
      out.write("                                ></label\r\n");
      out.write("                              >\r\n");
      out.write("                              <label class=\"box-check-input\"\r\n");
      out.write("                                ><input\r\n");
      out.write("                                  type=\"checkbox\"\r\n");
      out.write("                                  class=\"likeTag\"\r\n");
      out.write("                                  name=\"mTag\"\r\n");
      out.write("                                  value=\"공무원\"\r\n");
      out.write("                                /><span\r\n");
      out.write("                                  ><img src=\"../assets/images/likeTag/공무원.png\" />공무원</span\r\n");
      out.write("                                ></label\r\n");
      out.write("                              >\r\n");
      out.write("                              <label class=\"box-check-input\"\r\n");
      out.write("                                ><input\r\n");
      out.write("                                  type=\"checkbox\"\r\n");
      out.write("                                  class=\"likeTag\"\r\n");
      out.write("                                  name=\"mTag\"\r\n");
      out.write("                                  value=\"대학수능\"\r\n");
      out.write("                                /><span\r\n");
      out.write("                                  ><img src=\"../assets/images/likeTag/대학수능.png\" />대학수능</span\r\n");
      out.write("                                ></label\r\n");
      out.write("                              >\r\n");
      out.write("                              <label class=\"box-check-input\"\r\n");
      out.write("                                ><input\r\n");
      out.write("                                  type=\"checkbox\"\r\n");
      out.write("                                  class=\"likeTag\"\r\n");
      out.write("                                  name=\"mTag\"\r\n");
      out.write("                                  value=\"자격증\"\r\n");
      out.write("                                /><span\r\n");
      out.write("                                  ><img src=\"../assets/images/likeTag/자격증.png\" />자격증</span\r\n");
      out.write("                                ></label\r\n");
      out.write("                              >\r\n");
      out.write("                              <label class=\"box-check-input\"\r\n");
      out.write("                                ><input\r\n");
      out.write("                                  type=\"checkbox\"\r\n");
      out.write("                                  class=\"likeTag\"\r\n");
      out.write("                                  name=\"mTag\"\r\n");
      out.write("                                  value=\"학교공부\"\r\n");
      out.write("                                /><span\r\n");
      out.write("                                  ><img src=\"../assets/images/likeTag/학교공부.png\" />학교공부</span\r\n");
      out.write("                                ></label\r\n");
      out.write("                              >\r\n");
      out.write("                              <label class=\"box-check-input\"\r\n");
      out.write("                                ><input\r\n");
      out.write("                                  type=\"checkbox\"\r\n");
      out.write("                                  class=\"likeTag\"\r\n");
      out.write("                                  name=\"mTag\"\r\n");
      out.write("                                  value=\"기타\"\r\n");
      out.write("                                /><span\r\n");
      out.write("                                  ><img src=\"../assets/images/likeTag/기타.png\" />기타</span\r\n");
      out.write("                                ></label\r\n");
      out.write("                              >\r\n");
      out.write("                              <label class=\"box-check-input\"\r\n");
      out.write("                                ><input\r\n");
      out.write("                                  type=\"checkbox\"\r\n");
      out.write("                                  class=\"likeTag\"\r\n");
      out.write("                                  name=\"mTag\"\r\n");
      out.write("                                  value=\"코딩\"\r\n");
      out.write("                                /><span\r\n");
      out.write("                                  ><img src=\"../assets/images/likeTag/코딩.png\" />코딩</span\r\n");
      out.write("                                ></label\r\n");
      out.write("                              >\r\n");
      out.write("                              <label class=\"box-check-input\"\r\n");
      out.write("                                ><input\r\n");
      out.write("                                  type=\"checkbox\"\r\n");
      out.write("                                  class=\"likeTag\"\r\n");
      out.write("                                  name=\"mTag\"\r\n");
      out.write("                                  value=\"이직\"\r\n");
      out.write("                                /><span\r\n");
      out.write("                                  ><img src=\"../assets/images/likeTag/이직.png\" />이직</span\r\n");
      out.write("                                ></label\r\n");
      out.write("                              >\r\n");
      out.write("                              <label class=\"box-check-input\"\r\n");
      out.write("                                ><input\r\n");
      out.write("                                  type=\"checkbox\"\r\n");
      out.write("                                  class=\"likeTag\"\r\n");
      out.write("                                  name=\"mTag\"\r\n");
      out.write("                                  value=\"자기계발\"\r\n");
      out.write("                                /><span\r\n");
      out.write("                                  ><img src=\"../assets/images/likeTag/자기계발.png\" />자기계발</span\r\n");
      out.write("                                ></label\r\n");
      out.write("                              >\r\n");
      out.write("\r\n");
      out.write("                              <button id=\"likeTag\">선택 완료</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Bottom -->\r\n");
      out.write("        <!-- header 넣음 -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /#page -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <a id=\"scroll-top\"></a>\r\n");
      out.write("    <script src=\"../assets/js/signup.js\"></script>\r\n");
      out.write("    <script src=\"../assets/js/likeTag.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
