# jsp
spring :
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location: d:/temp/
  profiles:
    active:
    - dblocal
    - redislocal
    - tomcatlocal
    - elasticlocal
    - kafkaLocal
    - mysqllocal
    profiles: elasticlocal
  elasticsearch:
    clusterName: luna-lms
    host: 127.0.0.1
    port: 9300
    resthost: 127.0.0.1
    restport: 9200 
      
      
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://13.209.89.141:3306/howstudy?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin1234

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.demo.vo
  
 

server.port: 8888