# jsp
spring :
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location: d:/temp/
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://13.209.89.141:3306/howstudy?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin1234

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.demo.vo
  
  fcm:
  certification: howstudy-a7c5d-firebase-adminsdk-ikh2j-b749936127.json

server.port: 8888