/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.4
 * Generated at: 2023-01-30 08:48:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<!--[if IE 8 ]><html class=\"ie\" xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-US\" lang=\"en-US\"> <![endif]-->\n");
      out.write("<!--[if (gte IE 9)|!(IE)]><!-->\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-US\" lang=\"en-US\">\n");
      out.write("<!--<![endif]-->\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  ");
 String pjName = "/howStudy"; 
      out.write("\n");
      out.write("    <!-- Basic Page Needs -->\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->\n");
      out.write("    <title>HOWSTUDY</title>\n");
      out.write("\n");
      out.write("    <meta name=\"author\" content=\"themesflat.com\">\n");
      out.write("\n");
      out.write("    <!-- Mobile Specific Metas -->\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n");
      out.write("\n");
      out.write("    <!-- Theme Style -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\n");
      out.write("\n");
      out.write("    <!-- Favicon and Touch Icons  -->\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/icon/Favicon.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"assets/icon/Favicon.png\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"body bg-section-style3 header-fixed is_dark\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div id=\"wrapper\">\n");
      out.write("        <div id=\"page\" class=\"clearfix\">\n");
      out.write("           \n");
      out.write("             \n");
      out.write("            <!-- title page -->\n");
      out.write("            <section class=\"flat-title-page home5\">\n");
      out.write("                <div class=\"overlay\"></div>\n");
      out.write("                <div class=\"themesflat-container\">\n");
      out.write("                    <div class=\"wrap-heading flat-slider d-flex align-items-center\">\n");
      out.write("                        <div class=\"content\">\n");
      out.write("                            <h2 class=\"mg-bt-11\"><span class=\"fill\">HOWSTUDY</span></h2>\n");
      out.write("                            <h1 class=\"heading\">언제 어디서나 온라인 스터디 카페                                                                                 \n");
      out.write("                            </h1>	\n");
      out.write("                            <p class=\"sub-heading mg-t-7 mg-bt-39\">서로 공부하는 모습을 보며 집중해서 공부할 수 있어요.\n");
      out.write("                            </p>\n");
      out.write("                            <div class=\"flat-bt-slider style2 flex\">\n");
      out.write("                                <a href=\"studyRoom/study\" class=\"sc-button header-slider style style-1 rocket fl-button pri-1\"><span>스터디룸\n");
      out.write("                                </span></a>\n");
      out.write("                                <a href=\"board/noticesangse?nNUM=1006\" class=\"sc-button header-slider style style-1 note fl-button pri-1\"><span>이용가이드\n");
      out.write("                                </span></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"swiper-container swiper mySwiper swiper-h\">\n");
      out.write("                            <div class=\"swiper-wrapper\">\n");
      out.write("                              \n");
      out.write("                              <div class=\"swiper-slide\">\n");
      out.write("                                <div class=\"swiper mySwiper1 swiper-v\">\n");
      out.write("                                  <div class=\"swiper-wrapper\">\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/1.jpg\" alt=\"Image\" ></div>\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/2.jpg\" alt=\"Image\" ></div>\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/3.jpg\" alt=\"Image\"></div>\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/4.jpg\" alt=\"Image\" ></div>\n");
      out.write("                                  </div>\n");
      out.write("                                </div>\n");
      out.write("                              </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"swiper-container swiper mySwiper swiper-h\">\n");
      out.write("                            <div class=\"swiper-wrapper\">\n");
      out.write("                              \n");
      out.write("                              <div class=\"swiper-slide\">\n");
      out.write("                                <div class=\"swiper mySwiper2 swiper-v\">\n");
      out.write("                                  <div class=\"swiper-wrapper\">\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/5.jpg\" alt=\"Image\"></div>\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/6.jpg\" alt=\"Image\"></div>\n");
      out.write("                                    <div class=\"swiper-slide\"><img  src=\"../assets/images/indexImage/7.jpg\" alt=\"Image\"></div>\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/8.jpg\" alt=\"Image\"></div>\n");
      out.write("                                  </div>\n");
      out.write("                                  <div class=\"swiper-pagination\"></div>\n");
      out.write("                                </div>\n");
      out.write("                              </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"swiper-container swiper mySwiper swiper-h\">\n");
      out.write("                            <div class=\"swiper-wrapper\">\n");
      out.write("                              \n");
      out.write("                              <div class=\"swiper-slide\">\n");
      out.write("                                <div class=\"swiper mySwiper1 swiper-v\">\n");
      out.write("                                  <div class=\"swiper-wrapper\">\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/9.jpg\" alt=\"Image\"></div>\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/10.jpg\"alt=\"Image\"></div>\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/11.jpg\" alt=\"Image\"></div>\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/12.jpg\" alt=\"Image\"></div>\n");
      out.write("                                  </div>\n");
      out.write("                                  <div class=\"swiper-pagination\"></div>\n");
      out.write("                                </div>\n");
      out.write("                              </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"swiper-container swiper mySwiper swiper-h end\">\n");
      out.write("                            <div class=\"swiper-wrapper\">\n");
      out.write("                              \n");
      out.write("                              <div class=\"swiper-slide\">\n");
      out.write("                                <div class=\"swiper mySwiper2 swiper-v\">\n");
      out.write("                                  <div class=\"swiper-wrapper\">\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/13.jpg\" alt=\"Image\"></div>\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/14.jpg\" alt=\"Image\"></div>\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/15.jpg\" alt=\"Image\"></div>\n");
      out.write("                                    <div class=\"swiper-slide\"><img src=\"../assets/images/indexImage/16.png\" alt=\"Image\"></div>\n");
      out.write("                                  </div>\n");
      out.write("                                  <div class=\"swiper-pagination\"></div>\n");
      out.write("                                </div>\n");
      out.write("                              </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                </div>                           \n");
      out.write("            </section>\n");
      out.write("            <!-- Footer 넣음-->\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
