/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.4
 * Generated at: 2023-01-30 03:59:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.studyRoom;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class createroom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 8 ]><html class=\"ie\" xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-US\" lang=\"en-US\"> <![endif]-->\r\n");
      out.write("<!--[if (gte IE 9)|!(IE)]><!-->\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-US\" lang=\"en-US\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("<!-- 한글 깨짐 방지-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    ");
 String pjName = "/howStudy"; 
      out.write("\r\n");
      out.write("    <!-- Basic Page Needs -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->\r\n");
      out.write("    <title>HOWSTUDY</title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"author\" content=\"themesflat.com\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Mobile Specific Metas -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme Style -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon and Touch Icons  -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/icon/Favicon.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"assets/icon/Favicon.png\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"body header-fixed is_dark connect-wal\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <div id=\"page\" class=\"clearfix\">\r\n");
      out.write("            <!-- header 넣음 -->\r\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write(" \r\n");
      out.write("\r\n");
      out.write("            <!-- Header --> \r\n");
      out.write("                \r\n");
      out.write("            <!-- title page -->\r\n");
      out.write("            <section class=\"flat-title-page inner\">\r\n");
      out.write("                <div class=\"overlay\"></div>\r\n");
      out.write("                <div class=\"themesflat-container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <div class=\"page-title-heading mg-bt-12\">\r\n");
      out.write("                                <h1 class=\"heading text-center\">스터디룸 생성</h1>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"breadcrumbs style2\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                  <li><a href=\"\">스터디룸</a></li>\r\n");
      out.write("                                  <li>스터디룸 생성</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                              </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>                    \r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"tf-create-item tf-section\">\r\n");
      out.write("                <div class=\"themesflat-container\">\r\n");
      out.write("                   \r\n");
      out.write("                         <div class=\"col-xl-12 col-lg-12 col-md-12 col-12\">\r\n");
      out.write("                             <div class=\"form-create-item\">\r\n");
      out.write("                                <div class=\"flat-tabs tab-create-item\">\r\n");
      out.write("                                    <div class=\"content-tab\">\r\n");
      out.write("                                        <div class=\"content-inner\">\r\n");
      out.write("                                                <form action=\"insertRoom\" enctype=\"multipart/form-data\" method=\"post\" id=\"roomForm\">\r\n");
      out.write("                                                    <h2 class=\"title-create-item\">스터디 만들기</h2><div><br/><br/>\r\n");
      out.write("                                                        \r\n");
      out.write("                                                    <input type=\"hidden\" id=\"mId\" name=\"mId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                                    <h4 class=\"title-create-item\">스터디 이름</h4>\r\n");
      out.write("                                                    <input type=\"text\" placeholder=\"제목을 입력 해 주세요\" name=\"sTitle\" id=\"sTitle\">\r\n");
      out.write("                                                    <p id=\"chkRoom\" name=\"chkRoom\" size=\"2\" style=\"font-size: small;\"></p>\r\n");
      out.write("\r\n");
      out.write("                                                    <h4 class=\"title-create-item\">Upload file</h4>\r\n");
      out.write("                                                    <label class=\"uploadFile\">\r\n");
      out.write("                                                        <span class=\"filename\">PNG, JPG, GIF, WEBP or MP4. Max 200mb.</span>\r\n");
      out.write("                                                        <input type=\"file\" class=\"inputfile form-control\" name=\"file\" id=\"file\">\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                    <p id=\"chkRoom1\" name=\"chkRoom1\" size=\"2\" style=\"font-size: small;\"></p>\r\n");
      out.write("\r\n");
      out.write("                                                    \r\n");
      out.write("                                                    <div style=\"display : inline-block; text-align: left;\">\r\n");
      out.write("                                                    <h4 class=\"title-create-item\">카테고리</h4>\r\n");
      out.write("                                                        <div class=\"inner-row-form style-2\" id=\"foc\">\r\n");
      out.write("                                                            <div class=\"seclect-box\">\r\n");
      out.write("                                                                <div id=\"item-create\" class=\"dropdown\">\r\n");
      out.write("                                                                    <a href=\"#\" class=\"btn-selector nolink\" id=\"ct\" >선택</a>\r\n");
      out.write("                                                                    <input type=\"hidden\" name=\"sCategory\" id=\"sCtaegoly\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("                                                                    <ul class=\"cate\">\r\n");
      out.write("                                                                        <li><span>취업</span></li>\r\n");
      out.write("                                                                        <li><span>독서</span></li>\r\n");
      out.write("                                                                        <li><span>어학</span></li>\r\n");
      out.write("                                                                        <li><span>임용</span></li>\r\n");
      out.write("                                                                        <li><span>공무원</span></li>\r\n");
      out.write("                                                                        <li><span>대학수능</span></li>\r\n");
      out.write("                                                                        <li><span>자격증</span></li>\r\n");
      out.write("                                                                        <li><span>학교공부</span></li>\r\n");
      out.write("                                                                        <li><span>기타</span></li>\r\n");
      out.write("                                                                        <li><span>코딩</span></li>\r\n");
      out.write("                                                                        <li><span>이직</span></li>\r\n");
      out.write("                                                                        <li><span>자기계발</span></li>\r\n");
      out.write("                                                                    </ul>\r\n");
      out.write("                                                                </div><p id=\"chkRoom2\" name=\"chkRoom2\" size=\"2\" style=\"font-size: small;\"></p>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div><br/><br/>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div style=\"display : inline-block; float: left;\"></div>\r\n");
      out.write("                                                    <h4 class=\"title-create-item\">참여인원</h4>\r\n");
      out.write("                                                        <div class=\"inner-row-form style-2\">\r\n");
      out.write("                                                            <div class=\"seclect-box\">\r\n");
      out.write("                                                                <div id=\"item-create2\" class=\"dropdown\">\r\n");
      out.write("                                                                    <a href=\"#\" class=\"btn-selector nolink\" id=\"num\">선택</a>\r\n");
      out.write("                                                                    <input type=\"hidden\" name=\"sPeopleNum\" id=\"sPeopleNum\" value=\"\">\r\n");
      out.write("                                                                   \r\n");
      out.write("                                                                    <ul class=\"peopleNum\">\r\n");
      out.write("                                                                        <li><span>1 명</span></li>\r\n");
      out.write("                                                                        <li><span>2 명</span></li>\r\n");
      out.write("                                                                        <li><span>3 명</span></li>\r\n");
      out.write("                                                                        <li><span>4 명</span></li>\r\n");
      out.write("                                                                    </ul>\r\n");
      out.write("                                                                </div><p id=\"chkRoom3\" name=\"chkRoom3\" size=\"2\" style=\"font-size: small;\"></p>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div><br/> \r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    \r\n");
      out.write("                                                    <h4 class=\"title-create-item\">스터디 에티켓</h4>\r\n");
      out.write("                                                    <textarea placeholder=\"“스터디룸의 에티켓을 정하여 입력해 주세요”\" name=\"sComment\" style=\"height: 240px;\" id=\"sComment\"></textarea>\r\n");
      out.write("                                                    <div class=\"row-form style-2\">\r\n");
      out.write("                                                        <div class=\"inner-row-form toggle\">\r\n");
      out.write("                                                            <h4 class=\"title-create-item toggle\">비밀번호</h4>\r\n");
      out.write("                                                            <div class=\"toggle\" style=\"margin-left: 26px; margin-bottom:-10%;\">\r\n");
      out.write("                                                                <input type=\"checkbox\" name=\"toggle1\" id=\"toggle1\" >\r\n");
      out.write("                                                                <label for=\"toggle1\">스위치</label>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <input type=\"text\" id=\"pass\" name=\"sPw\" style=\"display:none;width:300px;\" placeholder=\"비밀번호를 입력해주세요.\" >\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <button id=\"btn\" name=\"btn\" >등록</button>\r\n");
      out.write("                                                </form>\r\n");
      out.write("                                                \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                             </div>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer 넣음-->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("        <!-- Bottom -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /#page -->\r\n");
      out.write("         <!-- Modal Popup Bid -->\r\n");
      out.write("         <div class=\"modal fade popup\" id=\"popup_bid_success\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"modal-body space-y-20 pd-40\">\r\n");
      out.write("                        <h3 class=\"text-center\">Your Bidding\r\n");
      out.write("                            Successfuly Added</h3>\r\n");
      out.write("                        <p class=\"text-center\">your bid <span class=\"price color-popup\">(4ETH) </span> has been listing to our database</p>\r\n");
      out.write("                        <a href class=\"btn btn-primary\"> Watch the listings</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal fade popup\" id=\"popup_bid\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"modal-body space-y-20 pd-40\">\r\n");
      out.write("                        <h3>Place a Bid</h3>\r\n");
      out.write("                        <p class=\"text-center\">You must bid at least <span class=\"price color-popup\">4.89 ETH</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\"\r\n");
      out.write("                            placeholder=\"00.00 ETH\">\r\n");
      out.write("                        <p>Enter quantity. <span class=\"color-popup\">5 available</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control quantity\" value=\"1\">\r\n");
      out.write("                        <div class=\"hr\"></div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                            <p> You must bid at least:</p>\r\n");
      out.write("                            <p class=\"text-right price color-popup\"> 4.89 ETH </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                            <p> Service free:</p>\r\n");
      out.write("                            <p class=\"text-right price color-popup\"> 0,89 ETH </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                            <p> Total bid amount:</p>\r\n");
      out.write("                            <p class=\"text-right price color-popup\"> 4 ETH </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#popup_bid_success\" data-dismiss=\"modal\" aria-label=\"Close\"> Place a bid</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <a id=\"scroll-top\"></a>\r\n");
      out.write("    <script src=\"../assets/js/studyRoom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
