/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.4
 * Generated at: 2023-01-31 07:28:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.studyRoom;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class searchItems_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/kosmo/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1672711024185L));
    _jspx_dependants.put("jar:file:/C:/Users/kosmo/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602841572000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("  \n");
      out.write("    <!DOCTYPE html>\n");
      out.write("    <!--[if IE 8]><html class=\"ie\" xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-US\" lang=\"en-US\"> <![endif]-->\n");
      out.write("    <!--[if (gte IE 9)|!(IE)]><!-->\n");
      out.write("    <html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-US\" lang=\"en-US\">\n");
      out.write("    <!--<![endif]-->\n");
      out.write("    <!-- 한글 깨짐 방지 -->\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("      <!-- Basic Page Needs -->\n");
      out.write("      <meta charset=\"utf-8\" />\n");
      out.write("      <!--[if IE]><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" /><![endif]-->\n");
      out.write("      <title>Axies | NFT Marketplace HTML Template</title>\n");
      out.write("\n");
      out.write("      <meta name=\"author\" content=\"themesflat.com\" />\n");
      out.write("\n");
      out.write("      <!-- Mobile Specific Metas -->\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\n");
      out.write("\n");
      out.write("      <!-- Theme Style -->\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"../assets/css/style.css\" />\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"../assets/css/flags.css\" />\n");
      out.write("\n");
      out.write("      <!-- Reponsive -->\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"../assets/css/responsive.css\" />\n");
      out.write("\n");
      out.write("      <!-- Favicon and Touch Icons  -->\n");
      out.write("      <link rel=\"shortcut icon\" href=\"../assets/icon/Favicon.png\" />\n");
      out.write("      <link rel=\"apple-touch-icon-precomposed\" href=\"../assets/icon/Favicon.png\" />\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body class=\"body header-fixed is_dark connect-wal\">\n");
      out.write("   \n");
      out.write("\n");
      out.write("      <div id=\"wrapper\">\n");
      out.write("        <div id=\"page\" class=\"clearfix\">\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("          <!-- title page -->\n");
      out.write("          <section class=\"flat-title-page inner\">\n");
      out.write("            <div class=\"overlay\"></div>\n");
      out.write("            <div class=\"themesflat-container\">\n");
      out.write("              <div class=\"row\">\n");
      out.write("                <div class=\"col-md-12\">\n");
      out.write("                  <div class=\"page-title-heading mg-bt-12\">\n");
      out.write("                    <h1 class=\"heading text-center\">검색 기록</h1>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"breadcrumbs style2\">\n");
      out.write("                    <ul>\n");
      out.write("                      <li><a href=\"study\">스터디룸</a></li>\n");
      out.write("                      <li>검색기록</li>\n");
      out.write("                    </ul>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </section>\n");
      out.write("\n");
      out.write("          <div class=\"tf-section sc-explore-1\">\n");
      out.write("            <div class=\"themesflat-container\">\n");
      out.write("              <div class=\"row\">\n");
      out.write("                <div class=\"col-md-12\">\n");
      out.write("                  <div class=\"wrap-box explore-1 flex mg-bt-40\">\n");
      out.write("\n");
      out.write("                    <div class=\"seclect-box style-2 box-right\"></div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"col-md-12 wrap-inner load-more text-center\">\n");
      out.write("                  <a href=\"#\" id=\"loadmore\" class=\"sc-button loadmore fl-button pri-3\"><span>더보기</span></a>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <!-- Footer -->\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\n");
      out.write("          <!-- header include -->\n");
      out.write("\n");
      out.write("          <!-- Bottom -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /#bottom -->\n");
      out.write("      </div>\n");
      out.write("      <!-- /#page -->\n");
      out.write("      <!-- /#wrapper -->\n");
      out.write("\n");
      out.write("      <a id=\"scroll-top\"></a>\n");
      out.write("\n");
      out.write("      <!-- Javascript -->\n");
      out.write("      <script src=\"../assets/js/jquery.min.js\"></script>\n");
      out.write("      <script src=\"../assets/js/jquery.easing.js\"></script>\n");
      out.write("      <script src=\"../assets/js/bootstrap.min.js\"></script>\n");
      out.write("      <script src=\"../assets/js/wow.min.js\"></script>\n");
      out.write("      <script src=\"../assets/js/plugin.js\"></script>\n");
      out.write("      <script src=\"../assets/js/shortcodes.js\"></script>\n");
      out.write("      <script src=\"../assets/js/main.js\"></script>\n");
      out.write("      <script src=\"../assets/js/swiper-bundle.min.js\"></script>\n");
      out.write("      <script src=\"../assets/js/web3.min.js\"></script>\n");
      out.write("      <script src=\"../assets/js/moralis.js\"></script>\n");
      out.write("      <script src=\"../assets/js/nft.js\"></script>\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/studyRoom/searchItems.jsp(69,16) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/studyRoom/searchItems.jsp(69,16) '${searchList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${searchList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/studyRoom/searchItems.jsp(69,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("vo");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                  <div class=\"fl-item col-xl-3 col-lg-4 col-md-6 col-sm-6\">\n");
            out.write("                    <div class=\"sc-card-product\">\n");
            out.write("\n");
            out.write("                      <div class=\"card-media\">\n");
            out.write("                        <a href=\"item-details.html\"><img src=\"../assets/images/studyRoom/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.sFile}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".png\" alt=\"Image\">\n");
            out.write("                      </div>\n");
            out.write("\n");
            out.write("                      <div class=\"card-title\">\n");
            out.write("                        <h5 class=\"style2\">\n");
            out.write("                          <a href=\"item-details.html\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.sTitle}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\n");
            out.write("                        </h5>\n");
            out.write("                        <div class=\"tags\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.sCategory}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\n");
            out.write("                      </div>\n");
            out.write("\n");
            out.write("                      <div class=\"meta-info\">\n");
            out.write("                        <div class=\"author\">\n");
            out.write("                          <div class=\"info\">\n");
            out.write("                            <h6><a href=\"author02.html\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.sComment}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></h6>\n");
            out.write("                          </div>\n");
            out.write("                        </div>\n");
            out.write("                        <div class=\"price\">\n");
            out.write("                          <span>총 인원수 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.sPeopleNum}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\n");
            out.write("                        </div>\n");
            out.write("                      </div>\n");
            out.write("\n");
            out.write("                      <div class=\"card-bottom\">\n");
            out.write("                        <a href=\"activity1.html\" class=\"view-history reload\">View</a>\n");
            out.write("                      </div>\n");
            out.write("                    </div>\n");
            out.write("                  </div>\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
